// <auto-generated />
namespace WaiwardDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ncrReqd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ncrReqd));
        
        string IMigrationMetadata.Id
        {
            get { return "201505180206426_ncrReqd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
